import type { Category, ServiceProvider, Service, Testimonial, HowItWorksStep } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Design & Creative',
    icon: '🎨',
    count: 1234,
    path: '/category/design',
  },
  {
    id: '2',
    name: 'Development',
    icon: '💻',
    count: 2456,
    path: '/category/development',
  },
  {
    id: '3',
    name: 'Content Writing',
    icon: '✍️',
    count: 1890,
    path: '/category/writing',
  },
  {
    id: '4',
    name: 'AI Services',
    icon: '🤖',
    count: 3421,
    path: '/category/ai',
  },
  {
    id: '5',
    name: 'Marketing',
    icon: '📊',
    count: 1567,
    path: '/category/marketing',
  },
  {
    id: '6',
    name: 'Business',
    icon: '💼',
    count: 2103,
    path: '/category/business',
  },
];

export const FEATURED_FREELANCERS: ServiceProvider[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    avatar: '👨‍💼',
    type: 'human',
    verified: true,
    completedGigs: 542,
    avgRating: 4.9,
    description: 'Full-stack developer with 8+ years experience',
    badges: ['Top Rated', 'Quick Response'],
  },
  {
    id: '2',
    name: 'Sarah Chen',
    avatar: '👩‍🎨',
    type: 'human',
    verified: true,
    completedGigs: 387,
    avgRating: 4.95,
    description: 'UI/UX Designer, specializing in web3 interfaces',
    badges: ['Premium Designer', 'Verified'],
  },
  {
    id: '3',
    name: 'Marcus Williams',
    avatar: '👨‍💻',
    type: 'human',
    verified: true,
    completedGigs: 612,
    avgRating: 4.88,
    description: 'Smart contract auditor and Solidity expert',
    badges: ['Top Rated', 'Security Expert'],
  },
  {
    id: '4',
    name: 'Emma Rodriguez',
    avatar: '👩‍💼',
    type: 'human',
    verified: true,
    completedGigs: 298,
    avgRating: 4.92,
    description: 'Content strategist and copywriter',
    badges: ['Creative Mind', 'Verified'],
  },
];

export const FEATURED_AI_AGENTS: ServiceProvider[] = [
  {
    id: 'ai1',
    name: 'CodeGenius AI',
    avatar: '🤖',
    type: 'ai',
    verified: true,
    completedGigs: 15234,
    avgRating: 4.85,
    description: 'AI agent specialized in code generation and optimization',
    badges: ['Always Available', 'Instant Delivery'],
  },
  {
    id: 'ai2',
    name: 'ContentFlow AI',
    avatar: '🤖',
    type: 'ai',
    verified: true,
    completedGigs: 12456,
    avgRating: 4.8,
    description: 'Content creation and SEO optimization AI',
    badges: ['24/7 Available', 'Scalable'],
  },
  {
    id: 'ai3',
    name: 'DesignMaster AI',
    avatar: '🤖',
    type: 'ai',
    verified: true,
    completedGigs: 9876,
    avgRating: 4.82,
    description: 'AI for design mockups and asset generation',
    badges: ['Creative', 'Fast Processing'],
  },
  {
    id: 'ai4',
    name: 'DataInsight AI',
    avatar: '🤖',
    type: 'ai',
    verified: true,
    completedGigs: 10543,
    avgRating: 4.87,
    description: 'Data analysis and visualization automation',
    badges: ['Accurate', 'Real-time'],
  },
];

export const FEATURED_SERVICES: Service[] = [
  {
    id: '1',
    title: 'Build Your NFT Smart Contract',
    description: 'Complete ERC-721 or ERC-1155 contract development with security audit',
    category: 'Development',
    price: 5.5,
    currency: 'ETH',
    provider: FEATURED_FREELANCERS[2],
    image: '🔐',
    rating: 4.95,
    reviews: 156,
    deliveryTime: 5,
    featured: true,
  },
  {
    id: '2',
    title: 'AI-Generated Product Images',
    description: '100 professional product images generated with AI in your style',
    category: 'AI Services',
    price: 0.8,
    currency: 'ETH',
    provider: FEATURED_AI_AGENTS[2],
    image: '🎨',
    rating: 4.88,
    reviews: 423,
    deliveryTime: 1,
    featured: true,
  },
  {
    id: '3',
    title: 'Full Website Redesign',
    description: 'Complete redesign of your web3 landing page with animations',
    category: 'Design & Creative',
    price: 3.2,
    currency: 'ETH',
    provider: FEATURED_FREELANCERS[1],
    image: '🌐',
    rating: 4.92,
    reviews: 89,
    deliveryTime: 7,
    featured: true,
  },
  {
    id: '4',
    title: 'SEO Content Strategy',
    description: '30-page SEO strategy and content calendar for your product',
    category: 'Marketing',
    price: 1200,
    currency: 'USDC',
    provider: FEATURED_AI_AGENTS[1],
    image: '📈',
    rating: 4.85,
    reviews: 234,
    deliveryTime: 3,
    featured: true,
  },
];

export const HOW_IT_WORKS: HowItWorksStep[] = [
  {
    id: '1',
    number: 1,
    title: 'Browse & Select',
    description: 'Browse thousands of services from verified sellers or let AI handle it instantly. Connect your wallet and explore the marketplace.',
    icon: '🔍',
  },
  {
    id: '2',
    number: 2,
    title: 'Secure Payment',
    description: 'Your payment is held in smart contract escrow. Only released when you approve the completed work or after delivery timeout.',
    icon: '🔒',
  },
  {
    id: '3',
    number: 3,
    title: 'Get Results',
    description: 'Receive your completed service instantly (AI) or on schedule (human). Rate and build seller reputation on the blockchain.',
    icon: '✅',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    author: 'James Chen',
    avatar: '👨‍💼',
    content: 'Got my entire dApp interface designed in under 48 hours. The AI quality was incredible and saved us weeks of work.',
    rating: 5,
    role: 'Founder, Web3Startup',
  },
  {
    id: '2',
    author: 'Lisa Moon',
    avatar: '👩‍💻',
    content: 'Found a smart contract expert instantly. The escrow system made me feel completely safe. 10/10 experience.',
    rating: 5,
    role: 'CTO, DeFiProtocol',
  },
  {
    id: '3',
    author: 'Marcus Thompson',
    avatar: '👨‍🎨',
    content: 'The AI agents are incredibly fast and affordable. We reduced our operational costs by 60% using Hustl3.',
    rating: 5,
    role: 'CEO, CreativeAgency',
  },
  {
    id: '4',
    author: 'Sofia Rodriguez',
    avatar: '👩‍🔬',
    content: 'As a freelancer, I love the transparent payment system and global reach. This is the future of work.',
    rating: 5,
    role: 'Freelance Designer',
  },
];

export const FOOTER_LINKS = {
  product: [
    { label: 'Browse Services', href: '#' },
    { label: 'Become a Seller', href: '#' },
    { label: 'How It Works', href: '#' },
    { label: 'Pricing', href: '#' },
  ],
  company: [
    { label: 'About Us', href: '#' },
    { label: 'Blog', href: '#' },
    { label: 'Careers', href: '#' },
    { label: 'Press', href: '#' },
  ],
  legal: [
    { label: 'Privacy Policy', href: '#' },
    { label: 'Terms of Service', href: '#' },
    { label: 'Cookie Policy', href: '#' },
    { label: 'Contact', href: '#' },
  ],
  social: [
    { label: 'Twitter', href: '#', icon: '𝕏' },
    { label: 'Discord', href: '#', icon: '💬' },
    { label: 'GitHub', href: '#', icon: '🐙' },
    { label: 'Telegram', href: '#', icon: '📱' },
  ],
};
