import type { Category, ServiceProvider, Service, Testimonial, HowItWorksStep } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Design & Creative',
    icon: 'Palette',
    count: 1234,
    path: '/explore?category=design',
  },
  {
    id: '2',
    name: 'Development',
    icon: 'Code',
    count: 2456,
    path: '/explore?category=development',
  },
  {
    id: '3',
    name: 'Content Writing',
    icon: 'PenTool',
    count: 1890,
    path: '/explore?category=writing',
  },
  {
    id: '4',
    name: 'AI Services',
    icon: 'Bot',
    count: 3421,
    path: '/explore?category=ai',
  },
  {
    id: '5',
    name: 'Marketing',
    icon: 'BarChart3',
    count: 1567,
    path: '/explore?category=marketing',
  },
  {
    id: '6',
    name: 'Business',
    icon: 'Briefcase',
    count: 2103,
    path: '/explore?category=business',
  },
];

export const FEATURED_FREELANCERS: ServiceProvider[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    avatar: 'Alex',
    type: 'human',
    verified: true,
    completedGigs: 542,
    avgRating: 4.9,
    description: 'Full-stack developer with 8+ years experience',
    badges: ['Top Rated', 'Quick Response'],
  },
  {
    id: '2',
    name: 'Sarah Chen',
    avatar: 'Sarah',
    type: 'human',
    verified: true,
    completedGigs: 387,
    avgRating: 4.95,
    description: 'UI/UX Designer, specializing in web3 interfaces',
    badges: ['Premium Designer', 'Verified'],
  },
  {
    id: '3',
    name: 'Marcus Williams',
    avatar: 'Marcus',
    type: 'human',
    verified: true,
    completedGigs: 612,
    avgRating: 4.88,
    description: 'Smart contract auditor and Solidity expert',
    badges: ['Top Rated', 'Security Expert'],
  },
  {
    id: '4',
    name: 'Emma Rodriguez',
    avatar: 'Emma',
    type: 'human',
    verified: true,
    completedGigs: 298,
    avgRating: 4.92,
    description: 'Content strategist and copywriter',
    badges: ['Creative Mind', 'Verified'],
  },
];

export const FEATURED_AI_AGENTS: ServiceProvider[] = [
  {
    id: 'ai1',
    name: 'CodeGenius AI',
    avatar: 'AI',
    type: 'ai',
    verified: true,
    completedGigs: 15234,
    avgRating: 4.85,
    description: 'AI agent specialized in code generation and optimization',
    badges: ['Always Available', 'Instant Delivery'],
  },
  {
    id: 'ai2',
    name: 'ContentFlow AI',
    avatar: 'AI',
    type: 'ai',
    verified: true,
    completedGigs: 12456,
    avgRating: 4.8,
    description: 'Content creation and SEO optimization AI',
    badges: ['24/7 Available', 'Scalable'],
  },
  {
    id: 'ai3',
    name: 'DesignMaster AI',
    avatar: 'AI',
    type: 'ai',
    verified: true,
    completedGigs: 9876,
    avgRating: 4.82,
    description: 'AI for design mockups and asset generation',
    badges: ['Creative', 'Fast Processing'],
  },
  {
    id: 'ai4',
    name: 'DataInsight AI',
    avatar: 'AI',
    type: 'ai',
    verified: true,
    completedGigs: 10543,
    avgRating: 4.87,
    description: 'Data analysis and visualization automation',
    badges: ['Accurate', 'Real-time'],
  },
];

export const FEATURED_SERVICES: Service[] = [
  {
    id: '1',
    title: 'Build Your NFT Smart Contract',
    description: 'Complete ERC-721 or ERC-1155 contract development with security audit',
    category: 'Development',
    price: 5.5,
    currency: 'ETH',
    provider: FEATURED_FREELANCERS[2],
    image: 'Shield',
    rating: 4.95,
    reviews: 156,
    deliveryTime: 5,
    featured: true,
  },
  {
    id: '2',
    title: 'AI-Generated Product Images',
    description: '100 professional product images generated with AI in your style',
    category: 'AI Services',
    price: 0.8,
    currency: 'ETH',
    provider: FEATURED_AI_AGENTS[2],
    image: 'Sparkles',
    rating: 4.88,
    reviews: 423,
    deliveryTime: 1,
    featured: true,
  },
  {
    id: '3',
    title: 'Full Website Redesign',
    description: 'Complete redesign of your web3 landing page with animations',
    category: 'Design & Creative',
    price: 3.2,
    currency: 'ETH',
    provider: FEATURED_FREELANCERS[1],
    image: 'Code',
    rating: 4.92,
    reviews: 89,
    deliveryTime: 7,
    featured: true,
  },
  {
    id: '4',
    title: 'SEO Content Strategy',
    description: '30-page SEO strategy and content calendar for your product',
    category: 'Marketing',
    price: 1200,
    currency: 'USDC',
    provider: FEATURED_AI_AGENTS[1],
    image: 'BarChart3',
    rating: 4.85,
    reviews: 234,
    deliveryTime: 3,
    featured: true,
  },
];

export const HOW_IT_WORKS: HowItWorksStep[] = [
  {
    id: '1',
    number: 1,
    title: 'Browse & Select',
    description: 'Browse thousands of services from verified sellers or let AI handle it instantly.',
    icon: 'Search',
  },
  {
    id: '2',
    number: 2,
    title: 'Secure Payment',
    description: 'Your payment is held in smart contract escrow. Only released when you approve.',
    icon: 'Shield',
  },
  {
    id: '3',
    number: 3,
    title: 'Get Results',
    description: 'Receive your completed service instantly (AI) or on schedule (human).',
    icon: 'CheckCircle',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    author: 'James Chen',
    avatar: 'JC',
    content: 'Got my entire dApp interface designed in under 48 hours. The AI quality was incredible.',
    rating: 5,
    role: 'Founder, Web3Startup',
  },
  {
    id: '2',
    author: 'Lisa Moon',
    avatar: 'LM',
    content: 'Found a smart contract expert instantly. The escrow system made me feel completely safe.',
    rating: 5,
    role: 'CTO, DeFiProtocol',
  },
  {
    id: '3',
    author: 'Marcus Thompson',
    avatar: 'MT',
    content: 'The AI agents are game-changing. Instant delivery at a fraction of the cost.',
    rating: 5,
    role: 'Indie Hacker',
  },
  {
    id: '4',
    author: 'Elena Rodriguez',
    avatar: 'ER',
    content: 'Hustl3 transformed how I run my agency. Best platform for web3 services.',
    rating: 5,
    role: 'Agency Owner',
  },
];

export const FOOTER_LINKS = {
  product: [
    { label: 'Explore', href: '/explore' },
    { label: 'Become Seller', href: '/seller' },
    { label: 'How It Works', href: '/how-it-works' },
    { label: 'Pricing', href: '/pricing' },
  ],
  company: [
    { label: 'About', href: '/about' },
    { label: 'Careers', href: '/careers' },
    { label: 'Blog', href: '/blog' },
    { label: 'Contact', href: '/contact' },
  ],
  legal: [
    { label: 'Privacy', href: '/privacy' },
    { label: 'Terms', href: '/terms' },
    { label: 'License', href: '/license' },
  ],
  social: [
    { label: 'Twitter', href: 'https://twitter.com/hustl3' },
    { label: 'Discord', href: 'https://discord.gg/hustl3' },
    { label: 'GitHub', href: 'https://github.com/hustl3' },
  ],
};